# -*- coding: utf-8 -*-
"""project_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aiEHFgzZpD0bBwGqw-GcbGieiuOKZsPt

# Parent Baseline vs Recovery-Proxy Model with Checks

This Colab-ready notebook reads CSV files from `/content/ParentCode_DS340W/data`, adds checks at each major step, builds:

- a parent baseline model
- a recovery-proxy improved model

and shows both in graph form.
"""

import os
import glob
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import Lasso
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

DATA_DIR = "/DS340W_Project/data"

def load_all_csvs(data_dir):
    csv_files = sorted(glob.glob(os.path.join(data_dir, "*.csv")))

    print("CSV count:", len(csv_files))

    if not csv_files:
        raise FileNotFoundError(f"No CSV files found in {data_dir}")

    frames = []
    for path in csv_files:
        try:
            df = pd.read_csv(path)
            df["source_file"] = os.path.basename(path)
            frames.append(df)
            print(f"Loaded: {os.path.basename(path)} | shape={df.shape}")
        except Exception as e:
            print(f"Skipping {os.path.basename(path)} because of error: {e}")

    if not frames:
        raise ValueError("CSV files were found, but none could be loaded.")

    merged = pd.concat(frames, ignore_index=True, sort=False)
    return merged

df_raw = load_all_csvs(DATA_DIR)

print("\nRaw combined shape:", df_raw.shape)
print("\nRaw columns:")
print(sorted(df_raw.columns.tolist()))

display(df_raw.head())

def find_first_match(columns, candidates):
    lower_cols = {c.lower().strip(): c for c in columns}

    for cand in candidates:
        key = cand.lower().strip()
        if key in lower_cols:
            return lower_cols[key]

    for cand in candidates:
        key = cand.lower().strip()
        for col in columns:
            if key in col.lower().strip():
                return col

    return None


def convert_comma_decimal(series):
    return pd.to_numeric(
        series.astype(str)
              .str.strip()
              .str.replace(",", ".", regex=False)
              .replace(["", "nan", "None", "NULL"], np.nan),
        errors="coerce"
    )

def standardize_columns(df):
    out = df.copy()

    colmap = {}

    athlete_col = find_first_match(out.columns, [
        "Athlete", "athlete", "Athlete Name", "athlete_name", "Name"
    ])
    date_col = find_first_match(out.columns, [
        "Date", "date"
    ])
    activity_col = find_first_match(out.columns, [
        "Activity Type", "activity_type", "Activity", "sport"
    ])
    tss_col = find_first_match(out.columns, [
        "Training Stress Score®", "Training Stress Score", "TSS", "stress score"
    ])

    if athlete_col:
        colmap[athlete_col] = "athlete"
    if date_col:
        colmap[date_col] = "date"
    if activity_col:
        colmap[activity_col] = "activity_type"
    if tss_col:
        colmap[tss_col] = "target_tss"

    out = out.rename(columns=colmap)

    if "athlete" not in out.columns:
        out["athlete"] = out["source_file"].str.replace(".csv", "", regex=False)

    if "date" in out.columns:
        out["date"] = pd.to_datetime(out["date"], errors="coerce")

    # Only convert object columns that look mostly numeric
    for col in out.columns:
        if col in ["athlete", "activity_type", "date", "source_file", "target_tss"]:
            continue

        if out[col].dtype == object:
            converted = convert_comma_decimal(out[col])
            non_null_original = out[col].notna().sum()
            non_null_converted = converted.notna().sum()

            # Convert only if a decent share survives numeric parsing
            if non_null_original > 0 and (non_null_converted / non_null_original) >= 0.6:
                out[col] = converted

    if "target_tss" in out.columns:
        out["target_tss"] = convert_comma_decimal(out["target_tss"])

    return out

df = standardize_columns(df_raw)

print("Columns after standardization:")
print(sorted(df.columns.tolist()))
display(df.head())

coverage = pd.DataFrame({
    "column": df.columns,
    "non_null_count": [df[c].notna().sum() for c in df.columns],
    "missing_pct": [df[c].isna().mean() * 100 for c in df.columns],
    "dtype": [str(df[c].dtype) for c in df.columns]
}).sort_values(["missing_pct", "column"])

display(coverage)

print("Total rows:", len(df))
print("Columns with at least 20% data:", (coverage["missing_pct"] <= 80).sum())
print("Numeric columns:", len(df.select_dtypes(include=[np.number]).columns))
print("Categorical/text columns:", len(df.select_dtypes(exclude=[np.number, "datetime64[ns]"]).columns))

def add_recovery_proxy_features(df):
    out = df.copy()

    sort_cols = [c for c in ["athlete", "activity_type", "date"] if c in out.columns]
    if sort_cols:
        out = out.sort_values(sort_cols).reset_index(drop=True)

    group_cols = ["athlete"]
    if "activity_type" in out.columns:
        group_cols.append("activity_type")

    grp = out.groupby(group_cols, dropna=False, group_keys=False)
    eps = 1e-6

    if "target_tss" in out.columns:
        out["proxy_load_3"] = grp["target_tss"].transform(lambda s: s.rolling(3, min_periods=1).mean())
        out["proxy_load_7"] = grp["target_tss"].transform(lambda s: s.rolling(7, min_periods=1).mean())
        out["proxy_load_lag1"] = grp["target_tss"].shift(1)

        out["proxy_tss_diff_1"] = grp["target_tss"].diff()
        out["proxy_tss_std_7"] = grp["target_tss"].transform(lambda s: s.rolling(7, min_periods=2).std())
    else:
        out["proxy_load_3"] = np.nan
        out["proxy_load_7"] = np.nan
        out["proxy_load_lag1"] = np.nan
        out["proxy_tss_diff_1"] = np.nan
        out["proxy_tss_std_7"] = np.nan

    if "target_tss" in out.columns:
        high_load = out["proxy_load_3"] > out["proxy_load_3"].median(skipna=True)
        out["proxy_fatigue_flag"] = high_load.astype(int)
    else:
        out["proxy_fatigue_flag"] = np.nan

    return out

df = add_recovery_proxy_features(df)

proxy_cols = [c for c in df.columns if c.startswith("proxy_")]
print("Proxy columns created:", proxy_cols)
display(df[proxy_cols].head())

if "target_tss" not in df.columns:
    raise ValueError("Could not find a TSS / Training Stress Score column.")

# Exclude obvious non-feature columns
exclude_cols = {
    "target_tss",
    "date",
    "source_file"
}

# Numeric features with reasonable coverage
numeric_features = [
    c for c in df.select_dtypes(include=[np.number]).columns
    if c not in exclude_cols and df[c].notna().sum() >= max(10, int(0.2 * len(df)))
]

# Categorical features with reasonable coverage
categorical_features = [
    c for c in df.select_dtypes(include=["object"]).columns
    if c not in exclude_cols and df[c].notna().sum() >= max(10, int(0.2 * len(df)))
]

# Baseline = all usable original features except proxy features
baseline_numeric = [c for c in numeric_features if not c.startswith("proxy_")]
baseline_categorical = categorical_features.copy()

# Improved = baseline + proxy features
improved_numeric = numeric_features.copy()
improved_categorical = categorical_features.copy()

print("Baseline numeric features:")
print(baseline_numeric)

print("\nBaseline categorical features:")
print(baseline_categorical)

print("\nImproved numeric features:")
print(improved_numeric)

print("\nImproved categorical features:")
print(improved_categorical)

def evaluate_model(df, numeric_features, categorical_features, target="target_tss", random_state=25):
    features = numeric_features + categorical_features

    if not features:
        print("No usable features found.")
        return None

    work = df[[target] + features].copy()
    work = work[work[target].notna()].copy()

    print("Rows before feature filtering:", len(work))

    if len(work) < 10:
        print("Not enough rows to run the model.")
        return None

    X = work[features]
    y = work[target]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=random_state
    )

    print("Train shape:", X_train.shape)
    print("Test shape:", X_test.shape)

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler())
            ]), numeric_features),
            ("cat", Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore"))
            ]), categorical_features)
        ]
    )

    pipe = Pipeline([
        ("preprocessor", preprocessor),
        ("model", Lasso(alpha=0.04))
    ])

    pipe.fit(X_train, y_train)
    preds = pipe.predict(X_test)

    metrics = {
        "MAE": mean_absolute_error(y_test, preds),
        "RMSE": np.sqrt(mean_squared_error(y_test, preds)),
        "R2": r2_score(y_test, preds)
    }

    pred_df = pd.DataFrame({
        "actual": y_test.values,
        "predicted": preds
    }).reset_index(drop=True)

    return metrics, pred_df, pipe

baseline_result = evaluate_model(df, baseline_numeric, baseline_categorical)
improved_result = evaluate_model(df, improved_numeric, improved_categorical)

if baseline_result is None:
    print("Baseline model could not run.")
else:
    baseline_metrics, baseline_preds, baseline_model = baseline_result
    print("Baseline metrics:", baseline_metrics)

if improved_result is None:
    raise ValueError("Improved model could not run.")
else:
    improved_metrics, improved_preds, improved_model = improved_result
    print("Improved metrics:", improved_metrics)

rows = []

if baseline_result is not None:
    rows.append({
        "Model": "Parent Baseline",
        **baseline_metrics
    })

rows.append({
    "Model": "Recovery-Proxy Improved",
    **improved_metrics
})

comparison = pd.DataFrame(rows)

print("Comparison table:")
display(comparison)

for metric in ["MAE", "RMSE", "R2"]:
    if metric in comparison.columns:
        plt.figure(figsize=(7, 4))
        comparison.set_index("Model")[metric].plot(kind="bar")
        plt.title(f"{metric} Comparison")
        plt.ylabel(metric)
        plt.xticks(rotation=20)
        plt.tight_layout()
        plt.show()

plt.figure(figsize=(7, 5))

all_series = []

if baseline_result is not None:
    plt.scatter(
        baseline_preds["actual"],
        baseline_preds["predicted"],
        alpha=0.7,
        label="Parent Baseline"
    )
    all_series.extend([baseline_preds["actual"], baseline_preds["predicted"]])

plt.scatter(
    improved_preds["actual"],
    improved_preds["predicted"],
    alpha=0.7,
    label="Recovery-Proxy Improved"
)
all_series.extend([improved_preds["actual"], improved_preds["predicted"]])

all_vals = pd.concat(all_series, ignore_index=True)
mn, mx = all_vals.min(), all_vals.max()

plt.plot([mn, mx], [mn, mx])
plt.xlabel("Actual TSS")
plt.ylabel("Predicted TSS")
plt.title("Actual vs Predicted")
plt.legend()
plt.tight_layout()
plt.show()

if baseline_result is not None:
    n = min(len(baseline_preds), len(improved_preds))
    plot_preds = pd.DataFrame({
        "Actual": baseline_preds["actual"].iloc[:n].reset_index(drop=True),
        "Baseline Predicted": baseline_preds["predicted"].iloc[:n].reset_index(drop=True),
        "Improved Predicted": improved_preds["predicted"].iloc[:n].reset_index(drop=True),
    })
else:
    n = len(improved_preds)
    plot_preds = pd.DataFrame({
        "Actual": improved_preds["actual"].iloc[:n].reset_index(drop=True),
        "Improved Predicted": improved_preds["predicted"].iloc[:n].reset_index(drop=True),
    })

plt.figure(figsize=(10, 5))
plt.plot(plot_preds.index, plot_preds["Actual"], label="Actual")

if "Baseline Predicted" in plot_preds.columns:
    plt.plot(plot_preds.index, plot_preds["Baseline Predicted"], label="Parent Baseline")

plt.plot(plot_preds.index, plot_preds["Improved Predicted"], label="Recovery-Proxy Improved")
plt.xlabel("Test Observation")
plt.ylabel("TSS")
plt.title("Prediction Comparison on Test Set")
plt.legend()
plt.tight_layout()
plt.show()

display(plot_preds.head(10))

comparison.to_csv("/content/model_metric_comparison.csv", index=False)
print("Saved: /content/model_metric_comparison.csv")

if baseline_result is not None:
    baseline_preds.to_csv("/content/baseline_predictions.csv", index=False)
    print("Saved: /content/baseline_predictions.csv")

improved_preds.to_csv("/content/improved_predictions.csv", index=False)
print("Saved: /content/improved_predictions.csv")